/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Secondary, SecondaryInterface } from "../Secondary";

const _abi = [
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "PrimaryTransferred",
    type: "event",
  },
  {
    constant: true,
    inputs: [],
    name: "primary",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "transferPrimary",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Secondary__factory {
  static readonly abi = _abi;
  static createInterface(): SecondaryInterface {
    return new utils.Interface(_abi) as SecondaryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Secondary {
    return new Contract(address, _abi, signerOrProvider) as Secondary;
  }
}
